// <auto-generated />
using System;
using FormulariosUAF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulariosUAF.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001130256_ConvencionNombresT")]
    partial class ConvencionNombresT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulariosUAF.Models.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("IN_CANTIDADACCESOSFALLIDOS_USUARIO");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_APELLIDOMATERNO_USUARIO");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_APELLIDOPATERNO_USUARIO");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_SELLOCONCURRENCIA_USUARIO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_USUARIO");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ST_EMAIL_USUARIO");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("BO_EMAILCONFIRMADO_USUARIO");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRECOMPLETO_USUARIO");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ACTIVO_USUARIO");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAULTIMOLOGIN_USUARIO");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("BO_BLOQUEOHABILITADO_USUARIO");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DT_FECHAFINBLOQUEO_USUARIO");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_NOMBRE_USUARIO");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ST_EMAILNORMALIZADO_USUARIO");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ST_NOMBREUSUARIONORMALIZADO_USUARIO");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_HASHCONTRASENA_USUARIO");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TELEFONO_USUARIO");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("BO_TELEFONOCONFIRMADO_USUARIO");

                    b.Property<string>("Rut")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ST_RUT_USUARIO");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_SELLOSEGURIDAD_USUARIO");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("BO_DOBLEFACTORHABILITADO_USUARIO");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ST_NOMBREUSUARIO_USUARIO");

                    b.Property<string>("VendorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CODVENDEDOR_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[ST_NOMBREUSUARIONORMALIZADO_USUARIO] IS NOT NULL");

                    b.ToTable("T_USUARIO", (string)null);
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IN_COD_AUDITORIA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_ACCION_AUDITORIA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_AUDITORIA");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CODENTIDAD_AUDITORIA");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOENTIDAD_AUDITORIA");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCIONIP_AUDITORIA");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_VALORESNUEVOS_AUDITORIA");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_VALORESANTERIORES_AUDITORIA");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_USERAGENT_AUDITORIA");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREUSUARIO_AUDITORIA");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestId");

                    b.ToTable("T_AUDITORIA");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.BeneficialOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_BENEFICIARIOFINAL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCION_BENEFICIARIOFINAL");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CIUDAD_BENEFICIARIOFINAL");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_PAIS_BENEFICIARIOFINAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_BENEFICIARIOFINAL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRECOMPLETO_BENEFICIARIOFINAL");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACION_BENEFICIARIOFINAL");

                    b.Property<bool>("IsBeneficialOwner")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ESBENEFICIARIOFINAL_BENEFICIARIOFINAL");

                    b.Property<bool>("IsEffectiveControl")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ESCONTROLEFECTIVO_BENEFICIARIOFINAL");

                    b.Property<bool>("IsPEP")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ESPEP_BENEFICIARIOFINAL");

                    b.Property<decimal>("ParticipationPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("NU_PORCENTAJEPARTICIPACION_BENEFICIARIOFINAL");

                    b.Property<string>("PepDetail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DETALLEPEP_BENEFICIARIOFINAL");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("IN_ORDEN_BENEFICIARIOFINAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_BENEFICIARIOFINAL");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("T_BENEFICIARIOFINAL");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_CLIENTE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ST_RAZONSOCIAL_CLIENTE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_CLIENTE");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CREADOPOR_CLIENTE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ACTIVO_CLIENTE");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ST_RUT_CLIENTE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_CLIENTE");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_MODIFICADOPOR_CLIENTE");

                    b.HasKey("Id");

                    b.HasIndex("RUT")
                        .IsUnique();

                    b.ToTable("T_CLIENTE");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Declarant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_DECLARANTE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CIUDAD_DECLARANTE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_DECLARANTE");

                    b.Property<DateTime>("DeclarationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHADECLARACION_DECLARANTE");

                    b.Property<bool>("DeclaresUnderOath")
                        .HasColumnType("bit")
                        .HasColumnName("BO_DECLARABAJOJURAMENTO_DECLARANTE");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_EMAIL_DECLARANTE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRE_DECLARANTE");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACION_DECLARANTE");

                    b.Property<string>("LastName1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_APELLIDOPATERNO_DECLARANTE");

                    b.Property<string>("LastName2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_APELLIDOMATERNO_DECLARANTE");

                    b.Property<int>("NationalityType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPONACIONALIDAD_DECLARANTE");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TELEFONO_DECLARANTE");

                    b.Property<string>("PlaceOfOrigin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_LUGARORIGEN_DECLARANTE");

                    b.Property<string>("RelationshipWithLegalEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RELACIONPERSONAJURIDICA_DECLARANTE");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<DateTime?>("SignatureDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAFIRMA_DECLARANTE");

                    b.Property<string>("SignatureFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRECOMPLETOFIRMA_DECLARANTE");

                    b.Property<string>("SignatureIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACIONFIRMA_DECLARANTE");

                    b.Property<string>("SignatureIpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCIONIPFIRMA_DECLARANTE");

                    b.Property<string>("SignatureUserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_USERAGENTFIRMA_DECLARANTE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_DECLARANTE");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("T_DECLARANTE");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.DeclaredPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_PERSONADECLARADA");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCION_PERSONADECLARADA");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CIUDAD_PERSONADECLARADA");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_PAIS_PERSONADECLARADA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_PERSONADECLARADA");

                    b.Property<string>("EffectiveControlDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DESCRIPCIONCONTROLEFECTIVO_PERSONADECLARADA");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRECOMPLETO_PERSONADECLARADA");

                    b.Property<bool>("HandlesCashOrFunds")
                        .HasColumnType("bit")
                        .HasColumnName("BO_MANEJAEFECTIVOFONDOS_PERSONADECLARADA");

                    b.Property<bool>("HasMinTenPercentParticipation")
                        .HasColumnType("bit")
                        .HasColumnName("BO_PARTICIPACIONMINDIEZPORCIENTO_PERSONADECLARADA");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACION_PERSONADECLARADA");

                    b.Property<bool>("IsEffectiveController")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ESCONTROLADOREFECTIVO_PERSONADECLARADA");

                    b.Property<bool>("IsPEP")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ESPEP_PERSONADECLARADA");

                    b.Property<decimal>("ParticipationPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("NU_PORCENTAJEPARTICIPACION_PERSONADECLARADA");

                    b.Property<string>("PepInstitution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_INSTITUCIONPEP_PERSONADECLARADA");

                    b.Property<string>("PepObservation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_OBSERVACIONPEP_PERSONADECLARADA");

                    b.Property<string>("PepPosition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CARGOPEP_PERSONADECLARADA");

                    b.Property<string>("PepRelationship")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RELACIONPEP_PERSONADECLARADA");

                    b.Property<int?>("PepType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPOPEP_PERSONADECLARADA");

                    b.Property<string>("PepTypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRETIPOPEP_PERSONADECLARADA");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPORELACION_PERSONADECLARADA");

                    b.Property<string>("RelationshipTypeOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPORELACIONOTRO_PERSONADECLARADA");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("IN_ORDEN_PERSONADECLARADA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_PERSONADECLARADA");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("T_PERSONADECLARADA");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_DOCUMENTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPO_DOCUMENTO");

                    b.Property<string>("DocumentTypeOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOOTRO_DOCUMENTO");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("IN_TAMANOBYTES_DOCUMENTO");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ACTIVO_DOCUMENTO");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOMIME_DOCUMENTO");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREARCHIVOORIGINAL_DOCUMENTO");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RUTAALMACENAMIENTO_DOCUMENTO");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("int")
                        .HasColumnName("IN_PROVEEDORALMACENAMIENTO_DOCUMENTO");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREARCHIVOALMACENADO_DOCUMENTO");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACARGA_DOCUMENTO");

                    b.Property<string>("UploadedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_IPCARGA_DOCUMENTO");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("IN_VERSION_DOCUMENTO");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("T_DOCUMENTO");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.EffectiveController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_CONTROLADOREFECTIVO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCION_CONTROLADOREFECTIVO");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CIUDAD_CONTROLADOREFECTIVO");

                    b.Property<string>("ControlDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DESCRIPCIONCONTROL_CONTROLADOREFECTIVO");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_PAIS_CONTROLADOREFECTIVO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_CONTROLADOREFECTIVO");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRECOMPLETO_CONTROLADOREFECTIVO");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACION_CONTROLADOREFECTIVO");

                    b.Property<bool>("IsPEP")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ESPEP_CONTROLADOREFECTIVO");

                    b.Property<decimal?>("ParticipationPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("NU_PORCENTAJEPARTICIPACION_CONTROLADOREFECTIVO");

                    b.Property<string>("PepDetail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DETALLEPEP_CONTROLADOREFECTIVO");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("IN_ORDEN_CONTROLADOREFECTIVO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_CONTROLADOREFECTIVO");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("T_CONTROLADOREFECTIVO");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.FileStorageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_ALMACENAMIENTOARCHIVO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_DOCUMENTO");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_METADATOS_ALMACENAMIENTOARCHIVO");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CLAVEALMACENAMIENTO_ALMACENAMIENTOARCHIVO");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RUTAALMACENAMIENTO_ALMACENAMIENTOARCHIVO");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("int")
                        .HasColumnName("IN_PROVEEDORALMACENAMIENTO_ALMACENAMIENTOARCHIVO");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACARGA_ALMACENAMIENTOARCHIVO");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("T_ALMACENAMIENTOARCHIVO");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.LegalEntityDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_DECLARACIONPERSONAJURIDICA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCION_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RAZONSOCIAL_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CIUDAD_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("CountryOfIncorporation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_PAISCONSTITUCION_DECLARACIONPERSONAJURIDICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_DECLARACIONPERSONAJURIDICA");

                    b.Property<int>("EntityType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPOENTIDAD_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("EntityTypeOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOENTIDADOTRO_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("LegalRepresentativeIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACIONREPRESENTANTELEGAL_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("LegalRepresentativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREREPRESENTANTELEGAL_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TELEFONO_DECLARACIONPERSONAJURIDICA");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RUT_DECLARACIONPERSONAJURIDICA");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_DECLARACIONPERSONAJURIDICA");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("T_DECLARACIONPERSONAJURIDICA");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_NOTIFICACION");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_NOTIFICACION");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("BO_LEIDA_NOTIFICACION");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_MENSAJE_NOTIFICACION");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHALECTURA_NOTIFICACION");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPO_NOTIFICACION");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("T_NOTIFICACION");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.PepDeclaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_DECLARACIONPEP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptsUnderOath")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ACEPTABAJOJURAMENTO_DECLARACIONPEP");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_DECLARACIONPEP");

                    b.Property<string>("DeclarantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREDECLARANTE_DECLARACIONPEP");

                    b.Property<DateTime>("DeclarationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHADECLARACION_DECLARACIONPEP");

                    b.Property<bool>("DeclaresPEP")
                        .HasColumnType("bit")
                        .HasColumnName("BO_DECLARAPEP_DECLARACIONPEP");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACION_DECLARACIONPEP");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_INSTITUCION_DECLARACIONPEP");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NACIONALIDAD_DECLARACIONPEP");

                    b.Property<string>("PepName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREPEP_DECLARACIONPEP");

                    b.Property<string>("PepReasonOther")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_MOTIVOPEPOTRO_DECLARACIONPEP");

                    b.Property<int?>("PepReasonType")
                        .HasColumnType("int")
                        .HasColumnName("IN_MOTIVOPEP_DECLARACIONPEP");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<DateTime>("SignatureDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAFIRMA_DECLARACIONPEP");

                    b.Property<string>("SignatureFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBRECOMPLETOFIRMA_DECLARACIONPEP");

                    b.Property<string>("SignatureIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACIONFIRMA_DECLARACIONPEP");

                    b.Property<string>("SignatureIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCIONIPFIRMA_DECLARACIONPEP");

                    b.Property<string>("SignatureUserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_USERAGENTFIRMA_DECLARACIONPEP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_DECLARACIONPEP");

                    b.Property<string>("VinculoType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOVINCULO_DECLARACIONPEP");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("T_DECLARACIONPEP");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_EMAILCLIENTE_SOLICITUD");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_CLIENTE");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TELEFONOCLIENTE_SOLICITUD");

                    b.Property<string>("ClientToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ST_TOKENCLIENTE_SOLICITUD");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACOMPLETADA_SOLICITUD");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_SOLICITUD");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CREADOPOR_SOLICITUD");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int")
                        .HasColumnName("IN_PASOACTUAL_SOLICITUD");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAVENCIMIENTO_SOLICITUD");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOTASINTERNAS_SOLICITUD");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("BO_ELIMINADO_SOLICITUD");

                    b.Property<string>("NetcarBusinessNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMERONEGOCIONETCAR_SOLICITUD");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAAPERTURA_SOLICITUD");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ST_NUMERO_SOLICITUD");

                    b.Property<int>("RequestType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPO_SOLICITUD");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAENVIO_SOLICITUD");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("IN_ESTADO_SOLICITUD");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAVENCIMIENTOTOKEN_SOLICITUD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_SOLICITUD");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_MODIFICADOPOR_SOLICITUD");

                    b.Property<string>("VendorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientToken")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("VendorUserId");

                    b.ToTable("T_SOLICITUD");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.RequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_HISTORIALESTADOSOLICITUD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACAMBIO_HISTORIALESTADOSOLICITUD");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CAMBIADOPOR_HISTORIALESTADOSOLICITUD");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("IN_ESTADONUEVO_HISTORIALESTADOSOLICITUD");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOTAS_HISTORIALESTADOSOLICITUD");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int")
                        .HasColumnName("IN_ESTADOANTERIOR_HISTORIALESTADOSOLICITUD");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("T_HISTORIALESTADOSOLICITUD");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.SignatureRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_FIRMA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certificate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CERTIFICADO_FIRMA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHACREACION_FIRMA");

                    b.Property<string>("DocumentHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_HASHDOCUMENTO_FIRMA");

                    b.Property<string>("FolioNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROFOLIO_FIRMA");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCIONIP_FIRMA");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_CODTRANSACCIONPROVEEDOR_FIRMA");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<string>("SignatureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_URL_FIRMA");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAFIRMA_FIRMA");

                    b.Property<string>("SignedPdfPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RUTAPDFFIRMADO_FIRMA");

                    b.Property<string>("SignerIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NUMEROIDENTIFICACIONFIRMANTE_FIRMA");

                    b.Property<string>("SignerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREFIRMANTE_FIRMA");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("IN_ESTADO_FIRMA");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPO_FIRMA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAMODIFICACION_FIRMA");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_USERAGENT_FIRMA");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("T_FIRMA");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.TaxFolderAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_ALERTACARPETATRIBUTARIA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertType")
                        .HasColumnType("int")
                        .HasColumnName("IN_TIPO_ALERTACARPETATRIBUTARIA");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit")
                        .HasColumnName("BO_RESUELTA_ALERTACARPETATRIBUTARIA");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_MENSAJE_ALERTACARPETATRIBUTARIA");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_SEVERIDAD_ALERTACARPETATRIBUTARIA");

                    b.Property<int>("TaxFolderAnalysisId")
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_ANALISISCARPETATRIBUTARIA");

                    b.HasKey("Id");

                    b.HasIndex("TaxFolderAnalysisId");

                    b.ToTable("T_ALERTACARPETATRIBUTARIA");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.TaxFolderAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_ANALISISCARPETATRIBUTARIA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_FECHAANALISIS_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("ExtractedActivity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_ACTIVIDADEXTRAIDA_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("ExtractedAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_DIRECCIONEXTRAIDA_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("ExtractedBusinessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RAZONSOCIALEXTRAIDA_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("ExtractedIssuedDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_FECHAEMISIONEXTRAIDA_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("ExtractedLegalRep")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_REPRESENTANTELEGALEXTRAIDO_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("ExtractedRut")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_RUTEXTRAIDO_ANALISISCARPETATRIBUTARIA");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TEXTOBRUTO_ANALISISCARPETATRIBUTARIA");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IN_COD_SOLICITUD");

                    b.Property<bool>("WasReadable")
                        .HasColumnType("bit")
                        .HasColumnName("BO_LEGIBLE_ANALISISCARPETATRIBUTARIA");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("T_ANALISISCARPETATRIBUTARIA");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_ROL");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_SELLOCONCURRENCIA_ROL");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ST_NOMBRE_ROL");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ST_NOMBRENORMALIZADO_ROL");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[ST_NOMBRENORMALIZADO_ROL] IS NOT NULL");

                    b.ToTable("T_ROL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_ROLCLAIM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOCLAIM_ROLCLAIM");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_VALORCLAIM_ROLCLAIM");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_ROL");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("T_ROLCLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IN_COD_USUARIOCLAIM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_TIPOCLAIM_USUARIOCLAIM");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_VALORCLAIM_USUARIOCLAIM");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("T_USUARIOCLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ST_PROVEEDORLOGIN_USUARIOLOGIN");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ST_CLAVEPROVEEDOR_USUARIOLOGIN");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_NOMBREVISIBLEPROVEEDOR_USUARIOLOGIN");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("T_USUARIOLOGIN", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_ROL");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("T_USUARIOROL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IN_COD_USUARIO");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ST_PROVEEDORLOGIN_USUARIOTOKEN");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ST_NOMBRE_USUARIOTOKEN");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ST_VALOR_USUARIOTOKEN");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("T_USUARIOTOKEN", (string)null);
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.AuditLog", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.BeneficialOwner", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany("BeneficialOwners")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Declarant", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithOne("Declarant")
                        .HasForeignKey("FormulariosUAF.Models.Domain.Declarant", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.DeclaredPerson", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany("DeclaredPersons")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Document", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany("Documents")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.EffectiveController", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany("EffectiveControllers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.FileStorageRecord", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Document", "Document")
                        .WithMany("StorageRecords")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.LegalEntityDeclaration", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithOne("LegalEntityDeclaration")
                        .HasForeignKey("FormulariosUAF.Models.Domain.LegalEntityDeclaration", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.PepDeclaration", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithOne("PepDeclaration")
                        .HasForeignKey("FormulariosUAF.Models.Domain.PepDeclaration", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Request", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Client", "Client")
                        .WithMany("Requests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormulariosUAF.Models.Domain.ApplicationUser", "VendorUser")
                        .WithMany("Requests")
                        .HasForeignKey("VendorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("VendorUser");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.RequestStatusHistory", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.SignatureRecord", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.TaxFolderAlert", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.TaxFolderAnalysis", "TaxFolderAnalysis")
                        .WithMany("Alerts")
                        .HasForeignKey("TaxFolderAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxFolderAnalysis");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.TaxFolderAnalysis", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.Request", "Request")
                        .WithOne("TaxFolderAnalysis")
                        .HasForeignKey("FormulariosUAF.Models.Domain.TaxFolderAnalysis", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormulariosUAF.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FormulariosUAF.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.ApplicationUser", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Client", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Document", b =>
                {
                    b.Navigation("StorageRecords");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.Request", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BeneficialOwners");

                    b.Navigation("Declarant");

                    b.Navigation("DeclaredPersons");

                    b.Navigation("Documents");

                    b.Navigation("EffectiveControllers");

                    b.Navigation("LegalEntityDeclaration");

                    b.Navigation("PepDeclaration");

                    b.Navigation("StatusHistory");

                    b.Navigation("TaxFolderAnalysis");
                });

            modelBuilder.Entity("FormulariosUAF.Models.Domain.TaxFolderAnalysis", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
